const seedNames = ["Alok Paul","Amar Paul","Ashok Paul","Arun Paul","Tarun Paul","Barun Paul","Samar Kumar Paul","Krishnendu Paul","Pradip Kumar Paul","Debo Prasad Paul","Bivas Paul","Subrata Paul","Arabindam Paul","Lt. Murari Prasad Paul","Ashis Paul","Nepal Paul","Rabindra Nath Paul","Gopal Paul","Amal Paul","Bimal Paul","Sohom Bhadra","Paromita Dutta","Kalyani Paul","Supriyo Pal","Shampa Chowdhury","Jayanta Chandra","Srabonti Banerjee","Madhuri Paul","Priyanka Paul","Shikha Paul","Bhadra Das","Brojorani Paul","Rubika Nag","Rita Das","Ananya Dey","Sanchari Paul","Debasish Paul","Subhasish Paul","Sukumar Pal","Mousumi Pal","Sadhan pal and Manoj Paul","Mouhua Marick","Poly Paul","Somnath Das","Tathagata Paul","Bikas Paul","Ranu Dutta","Protima (Suravi Sarkar)","Kathamo Puja (Dwipanwita Paul)","Mud utensils (Priyanka Paul)","Sandhi Puja (Avijit Paul)","Flower (Sudipto Paul)","Purohit (Nirmalya Pal)","Samiran Dutta","Kalyani Paul","Boli Fruits & Dodhikorma (Manoj Paul)","Anjana Paul","Mat & Pillow (Dwipanwita Paul)","Vasan Snacks (Suvajit Pal)","Bikas Paul (Milk & curd)","Fuchka contributors","Kathamo Tola Snacks (Bhamari Pal)","ghoter mala (Alok Paul)","Supriyo Paul","Atanu Nag","Sudipta Pal","Arun Kr Pal","Bener Dokan (Santu Paul)"];
const seedItems = ["Pandal (Samar da)","Painting of Thakur Dalan","Electric permission","Mud utensils","Chandmala","Kathamo Puja","Protima","Steel Plate & glass","Dhuti & urni","Mat & Pillow","Flower","Field cleaning","Milk & curd (panchomi)","Meal for poto","Fruits and green coconut","Dhaki toto fare","Dhaki","Sandhi Puja (including Lotus)","ghoter mala","Purohit","Oil & dhuno","Fuchka","Banana and Cucumber","Bijoyar Sweets","Vasan Snacks","Kathamo Tola Snacks","Plastic Mala","Bliching Powder","Puja Sweets","Bamboo Cutting","Bisorjon convenience","Masi (Pujo helper)","Van fare for Kathamo tola","Boli (Khokon Da)","Vegetable","Grocery for Khichuri","Bablu & Nile for khichuri","Laxmi Puja expenses","Water expenses for Khicuri","Van fare for Gangajol","Laxmi Puja vasan expenses","Rope for vasan","Boli Fruits & Dodhikorma","Bener Dokan"];
const seedCategories = ["Subscription","Cash Donation","Misc. Donation","Expense"];
const seedSubscription = [{name:"Alok Paul",amount:2500},{name:"Amar Paul",amount:2500},{name:"Ashok Paul",amount:5000},{name:"Arun Paul",amount:3333},{name:"Tarun Paul",amount:3333},{name:"Barun Paul",amount:3340},{name:"Samar Kumar Paul",amount:3000},{name:"Krishnendu Paul",amount:200},{name:"Pradip Kumar Paul",amount:525},{name:"Debo Prasad Paul",amount:500},{name:"Bivas Paul",amount:1000},{name:"Subrata Paul",amount:1000},{name:"Arabindam Paul",amount:3340},{name:"Lt. Murari Prasad Paul",amount:3333},{name:"Ashis Paul",amount:1135},{name:"Nepal Paul",amount:2000},{name:"Rabindra Nath Paul",amount:2000},{name:"Gopal Paul",amount:2000},{name:"Amal Paul",amount:1100},{name:"Bimal Paul",amount:2000},{name:"Sohom Bhadra",amount:500},{name:"Paromita Dutta",amount:501},{name:"Kalyani Paul",amount:501},{name:"Supriyo Pal",amount:1500},{name:"Shampa Chowdhury",amount:1000},{name:"Jayanta Chandra",amount:1000},{name:"Srabonti Banerjee",amount:700},{name:"Madhuri Paul",amount:500},{name:"Priyanka Paul",amount:700},{name:"Shikha Paul",amount:600},{name:"Bhadra Das",amount:300},{name:"Brojorani Paul",amount:200},{name:"Rubika Nag",amount:500},{name:"Rita Das",amount:500},{name:"Ananya Dey",amount:500},{name:"Sanchari Paul",amount:2000},{name:"Debasish Paul",amount:1135},{name:"Subhasish Paul",amount:1135},{name:"Sukumar Pal",amount:2000},{name:"Mousumi Pal",amount:2000},{name:"Sadhan pal and Manoj Paul",amount:2000},{name:"Mouhua Marick",amount:2000},{name:"Poly Paul",amount:250},{name:"Somnath Das",amount:500},{name:"Tathagata Paul",amount:1000},{name:"Bikas Paul",amount:1000},{name:"Ranu Dutta",amount:500}];
const selectedYear = new URLSearchParams(location.search).get('year');
const state = {activeLedger:'pujo',activeYear:selectedYear==='2025'?'2025':'2026',entries:[],entriesByYear:{'2025':[],'2026':[]},masters:{names:[...new Set(seedNames)],items:[...seedItems],categories:[...seedCategories]},ledgers:{},syncToken:''};
const ledgerLabels={pujo:'Pujo Ledger',meal:'Meal System',maintenance:'Maintenance System'};
function emptyLedger(){return {entriesByYear:{'2025':[],'2026':[]},masters:{names:[],items:[],categories:[...seedCategories]}}}
function syncActiveLedger(){state.ledgers[state.activeLedger]={entriesByYear:state.entriesByYear,masters:state.masters}}
function activateLedger(id){const ledger=state.ledgers[id]||emptyLedger();state.activeLedger=id;state.entriesByYear=ledger.entriesByYear;state.masters=ledger.masters;state.entries=state.entriesByYear[state.activeYear]||[];if($('#ledgerSelect'))$('#ledgerSelect').value=id}
let cloudSyncReady=false;let cloudSyncPaused=false;let cloudSyncTimer=null;let cloudPushPromise=Promise.resolve();
const cloudRemoteApi='https://pujo-ledger-production.up.railway.app/api/state';const localServer=(location.hostname==='127.0.0.1'||location.hostname==='localhost')&&['3000','4173'].includes(location.port);const cloudApi=localServer||location.hostname==='pujo-ledger-production.up.railway.app'?'/api/state':cloudRemoteApi;
const dbRequest = indexedDB.open('pujo-ledger',1); dbRequest.onupgradeneeded = e => e.target.result.createObjectStore('state'); dbRequest.onsuccess = e => { state.db=e.target.result; const req=state.db.transaction('state').objectStore('state').get('app'); req.onsuccess=()=>{ if(req.result){state.syncToken=req.result.syncToken||'';state.activeYear=req.result.activeYear||'2026';state.activeLedger=req.result.activeLedger||'pujo';state.ledgers=req.result.ledgers||{pujo:{entriesByYear:req.result.entriesByYear||{'2025':req.result.entries||[],'2026':[]},masters:req.result.masters||state.masters}};activateLedger(state.activeLedger);} else { seedInitialEntries(); } state.entries=state.entriesByYear[state.activeYear]||[]; render();cloudSyncReady=true;const syncCode=$('#syncCode');if(syncCode)syncCode.value=state.syncToken;if(state.syncToken)setTimeout(()=>pullCloudState(),650); }; };
function save(){ if(!state.db)return; state.entriesByYear[state.activeYear]=state.entries;syncActiveLedger();state.db.transaction('state','readwrite').objectStore('state').put({activeLedger:state.activeLedger,activeYear:state.activeYear,ledgers:state.ledgers,entriesByYear:state.entriesByYear,masters:state.masters,syncToken:state.syncToken},'app'); if(cloudSyncReady&&!cloudSyncPaused&&state.syncToken)queueCloudSync(); }
function flushCloudSync(){if(!state.syncToken)return;clearTimeout(cloudSyncTimer);cloudPushPromise=cloudPushPromise.catch(()=>{}).then(()=>pushCloudState())}
function queueCloudSync(){clearTimeout(cloudSyncTimer);cloudSyncTimer=setTimeout(flushCloudSync,250);}
async function pushCloudState(){if(!state.syncToken)return;try{syncActiveLedger();const response=await fetch(cloudApi,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${state.syncToken}`},body:JSON.stringify({activeLedger:state.activeLedger,activeYear:state.activeYear,ledgers:state.ledgers,entriesByYear:state.entriesByYear,masters:state.masters})});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||'Cloud save failed');toast('Saved to cloud');}catch(error){toast(error.message||'Cloud save failed');}}
async function requestCloudState(attempt=0){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(`${cloudApi}?t=${Date.now()}`,{headers:{Authorization:`Bearer ${state.syncToken}`,Accept:'application/json'},cache:'no-store',signal:controller.signal});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||`Cloud load failed (${response.status})`);return result;}catch(error){if(attempt<2){await new Promise(resolve=>setTimeout(resolve,700*(attempt+1)));return requestCloudState(attempt+1)}throw error}finally{clearTimeout(timeout)}}
async function pullCloudState(){if(!state.syncToken)return toast('Enter a sync code first');const button=$('#pullSyncBtn'),selectedLedger=state.activeLedger;clearTimeout(cloudSyncTimer);cloudSyncPaused=true;if(button){button.disabled=true;button.textContent='Loading…'}try{const result=await requestCloudState();if(!result.payload)throw new Error('No cloud backup found yet');state.activeYear=result.payload.activeYear||state.activeYear;if(result.payload.ledgers){state.ledgers=result.payload.ledgers;activateLedger(selectedLedger)}else{state.entriesByYear=result.payload.entriesByYear||state.entriesByYear;state.masters=result.payload.masters||state.masters;state.entries=state.entriesByYear[state.activeYear]||[]}save();render();toast(`Cloud loaded · ${ledgerLabels[state.activeLedger]||'current ledger'}`)}catch(error){toast(error.name==='AbortError'?'Cloud is taking too long. Please try again.':error.message||'Unable to load cloud data')}finally{cloudSyncPaused=false;if(button){button.disabled=false;button.textContent='Load from cloud'}}}
function seedInitialEntries(){ state.entriesByYear['2025']=seedSubscription.map((x,i)=>({id:crypto.randomUUID(),type:'income',date:'2025-09-'+String(Math.min(30,Math.max(1, i+1))).padStart(2,'0'),amount:x.amount,person:x.name,category:'Subscription',mode:'Cash',notes:'Imported from 2025 balance sheet',images:[]})); state.entriesByYear['2026']=[]; state.activeYear='2026'; state.entries=[];state.ledgers.pujo={entriesByYear:state.entriesByYear,masters:state.masters};save(); }
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0); const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const income=state.entries.filter(e=>e.type!=='expense').reduce((a,e)=>a+Number(e.amount),0), expense=state.entries.filter(e=>e.type==='expense').reduce((a,e)=>a+Number(e.amount),0); $('#yearTitle').textContent=state.activeYear;$('#ledgerTitle').textContent=ledgerLabels[state.activeLedger]||'Ledger'; $$('.year-btn').forEach(b=>b.classList.toggle('active',b.dataset.year===state.activeYear)); $('#incomeTotal').textContent=money(income);$('#expenseTotal').textContent=money(expense);$('#balanceTotal').textContent=money(income-expense);$('#incomeCount').textContent=state.entries.filter(e=>e.type!=='expense').length+' entries';$('#expenseCount').textContent=state.entries.filter(e=>e.type==='expense').length+' entries'; renderEntries($('#recentEntries'),state.entries.slice().sort(sortDate).slice(0,8)); renderEntries($('#allEntries'),filtered()); $('#emptyState').classList.toggle('hidden',state.entries.length>0); renderMasters(); fillDatalists();}
function switchYear(year){if(year===state.activeYear)return;save();state.activeYear=year;state.entries=state.entriesByYear[year]||[];showView('dashboard');render();toast('Switched to '+year+' ledger')}
function switchLedger(id){if(id===state.activeLedger)return;save();state.activeLedger=id;const ledger=state.ledgers[id]||emptyLedger();state.entriesByYear=ledger.entriesByYear;state.masters=ledger.masters;state.entries=state.entriesByYear[state.activeYear]||[];showView('dashboard');render();save();toast('Switched to '+ledgerLabels[id])}
function sortDate(a,b){return String(b.date).localeCompare(String(a.date))} function filtered(){const q=($('#searchInput')?.value||'').toLowerCase(),t=$('#typeFilter')?.value||'all',m=$('#modeFilter')?.value||'all';return state.entries.filter(e=>(t==='all'||e.type===t)&&(m==='all'||e.mode===m)&&(!q||[e.person,e.particular,e.notes,e.category].join(' ').toLowerCase().includes(q))).sort(sortDate)}
function entryMeta(e){const parts=e.type==='donation'?[e.donationKind==='cash'?'Cash Donation':'Item Donation',e.particular||'']:[e.date,e.mode];if(e.notes)parts.push(e.notes);if(e.images?.length)parts.push('📎 '+e.images.length);return parts.filter(Boolean).map(esc).join(' · ')}
function renderEntries(node,list){if(!node)return;node.innerHTML=list.map(e=>`<div class="entry" data-entry-id="${e.id}"><div class="entry-icon ${e.type}">${e.type==='expense'?'↗':'↙'}</div><div><div class="entry-name">${esc(e.type==='expense'?e.particular:e.person||'Donation')}</div><div class="entry-meta">${entryMeta(e)}</div>${e.images?.length?`<div class="entry-images">${e.images.map((image,index)=>`<button class="entry-image-link" type="button" data-image="${esc(image)}"><img src="${esc(image)}" alt="Receipt ${index+1}"></button>`).join('')}</div>`:''}</div><div class="entry-amount ${e.type==='expense'?'expense':''}">${e.type==='expense'?'−':'+'}${money(e.amount)}</div><div class="entry-actions"><button class="mini-btn" data-edit="${e.id}">Edit</button><button class="mini-btn" data-delete="${e.id}">Delete</button></div></div>`).join('')||'<div class="empty"><p>No matching entries found.</p></div>'}
function renderMasters(){[['names','namesList'],['items','itemsList'],['categories','categoriesList']].forEach(([key,id])=>{$('#'+id).innerHTML=state.masters[key].map((x,i)=>`<div class="master-item"><span>${esc(x)}</span><button class="mini-btn" data-remove-master="${key}" data-index="${i}">Remove</button></div>`).join('')})}
function fillDatalists(){ $('#nameSuggestions').innerHTML=state.masters.names.map(x=>`<option value="${esc(x)}">`).join('');$('#itemSuggestions').innerHTML=state.masters.items.map(x=>`<option value="${esc(x)}">`).join('');$('#entryCategory').innerHTML=state.masters.categories.map(x=>`<option>${esc(x)}</option>`).join(''); }
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function imagePreviewMarkup(images){return images.map((x,i)=>`<div class="image-thumb"><button class="entry-image-link" type="button" data-image="${esc(x)}"><img src="${esc(x)}" alt="Reference photo ${i+1}"></button><button class="image-remove" type="button" data-remove-image aria-label="Remove image">×</button></div>`).join('')}
function openEntry(entry){$('#entryForm').reset();$('#entryId').value=entry?.id||'';$('#dialogTitle').textContent=entry?'Edit entry':'New entry';$('#entryDate').value=entry?.date||new Date().toISOString().slice(0,10);$('#entryAmount').value=entry?.amount||'';$('#entryPerson').value=entry?.person||'';$('#entryParticular').value=entry?.particular||'';$('#entryCategory').value=entry?.category||state.masters.categories[0];$('#entryMode').value=entry?.mode||'Cash';$('#entryNotes').value=entry?.notes||''; $(`input[name="entryType"][value="${entry?.type||'income'}"]`).checked=true; toggleType(); $('#imagePreview').innerHTML=imagePreviewMarkup(entry?.images||[]); $('#entryDialog').showModal()}
function toggleType(){const type=$('input[name="entryType"]:checked').value;const income=type==='income',donation=type==='donation';$('#personField').classList.toggle('hidden',!income&&!donation);$('#particularField').classList.toggle('hidden',income||donation);$('#donationDetailField')?.classList.toggle('hidden',!donation);$('#entryPerson').required=income||donation;$('#entryParticular').required=!income&&!donation;$('#entryAmount').required=!(donation&&$('#donationKind')?.value==='item')}
async function imagesToData(fileList){return Promise.all([...fileList].map(f=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(f)})))}
$('#entryImages')?.addEventListener('change',async e=>{const selected=await imagesToData(e.target.files);if(!selected.length)return;const current=[...$('#imagePreview').querySelectorAll('.entry-image-link')].map(button=>button.dataset.image);$('#imagePreview').innerHTML=imagePreviewMarkup([...current,...selected]);});
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-view-target]').forEach(b=>b.onclick=()=>showView(b.dataset.viewTarget));$$('[data-year]').forEach(b=>b.onclick=()=>switchYear(b.dataset.year));$('#ledgerSelect')?.addEventListener('change',e=>switchLedger(e.target.value));function showView(view){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('hidden',v.id!==view+'View'))}
$$('[data-action="new"]').forEach(b=>b.onclick=()=>openEntry());$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('input[name="entryType"]').forEach(x=>x.onchange=toggleType);$('#searchInput').oninput=render;$('#typeFilter').onchange=render;$('#modeFilter').onchange=render;
$('#entryForm').onsubmit=async e=>{e.preventDefault();const id=$('#entryId').value||crypto.randomUUID(),old=state.entries.find(x=>x.id===id),type=$('input[name="entryType"]:checked').value,added=await imagesToData($('#entryImages').files);const item={id,type,date:$('#entryDate').value,amount:Number($('#entryAmount').value),person:type==='income'?$('#entryPerson').value.trim():'',particular:type==='expense'?$('#entryParticular').value.trim():'',category:$('#entryCategory').value,mode:$('#entryMode').value,notes:$('#entryNotes').value.trim(),images:[...(old?.images||[]),...added]};state.entries=old?state.entries.map(x=>x.id===id?item:x):[item,...state.entries];[item.person,item.particular].forEach((v,i)=>{if(v){const k=i===0?'names':'items';if(!state.masters[k].includes(v))state.masters[k].push(v)}});save();render();$('#entryDialog').close();toast(old?'Entry updated':'Entry saved')};
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]'),rm=e.target.closest('[data-remove-master]');if(edit)openEntry(state.entries.find(x=>x.id===edit.dataset.edit));if(del){if(confirm('Delete this entry?')){state.entries=state.entries.filter(x=>x.id!==del.dataset.delete);save();render();toast('Entry deleted')}}if(rm){const k=rm.dataset.removeMaster;if(confirm('Remove this suggestion from the master list?')){state.masters[k].splice(Number(rm.dataset.index),1);save();render()}}});
let masterKind='names';$$('[data-master]').forEach(b=>b.onclick=()=>{masterKind=b.dataset.master;$('#masterTitle').textContent='Add '+(masterKind==='names'?'contributor name':masterKind==='items'?'expense particular':'category');$('#masterValue').value='';$('#masterDialog').showModal()});$('#masterForm').onsubmit=e=>{e.preventDefault();const v=$('#masterValue').value.trim();if(v&&!state.masters[masterKind].includes(v)){state.masters[masterKind].push(v);save();render();toast('Added to master list')}$('#masterDialog').close()};
$('#exportBtn').onclick=()=>{save();const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),entriesByYear:state.entriesByYear,masters:state.masters})],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pujo-ledger-backup.json';a.click();URL.revokeObjectURL(a.href);toast('Backup downloaded')};$('#importInput').onchange=async e=>{const data=JSON.parse(await e.target.files[0].text());if(!data.masters||(!data.entriesByYear&&!data.entries)) return toast('Invalid backup file');state.entriesByYear=data.entriesByYear||{'2025':data.entries,'2026':[]};state.masters=data.masters;state.entries=state.entriesByYear[state.activeYear]||[];save();render();toast('Backup restored')};$('#printBtn').onclick=()=>{showView('entries');setTimeout(()=>window.print(),50)};
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js');let deferredInstall;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}};
if(selectedYear){setTimeout(()=>{state.activeYear=selectedYear;state.entries=state.entriesByYear[selectedYear]||[];render();},300)}
let groupingAllEntries=false;
function groupAllEntries(){const node=$('#allEntries');if(!node||groupingAllEntries)return;const entries=[...node.querySelectorAll('.entry')];if(!entries.length)return;const signature=entries.map(x=>x.outerHTML).join('');if(node.dataset.signature===signature)return;node.dataset.signature=signature;const income=entries.filter(x=>!x.querySelector('.entry-amount.expense')),expense=entries.filter(x=>x.querySelector('.entry-amount.expense'));groupingAllEntries=true;node.innerHTML=`${income.length?'<div class="group-title income-title"><span>↙</span> Income <em>'+income.length+' entries</em></div>'+income.map(x=>x.outerHTML).join(''):''}${expense.length?'<div class="group-title expense-title"><span>↗</span> Expenses <em>'+expense.length+' entries</em></div>'+expense.map(x=>x.outerHTML).join(''):''}`;groupingAllEntries=false;}
new MutationObserver(groupAllEntries).observe($('#allEntries'),{childList:true});
let stackingGroups=false;
function stackGroups(){const node=$('#allEntries');if(!node||stackingGroups)return;const entries=[...node.querySelectorAll('.entry')];if(!entries.length)return;const signature=entries.map(x=>x.outerHTML).join('');if(node.dataset.stackSignature===signature)return;node.dataset.stackSignature=signature;const income=entries.filter(x=>!x.querySelector('.entry-amount.expense')),expense=entries.filter(x=>x.querySelector('.entry-amount.expense'));stackingGroups=true;node.innerHTML=`${income.length?'<section class="entry-group income-group"><div class="group-title income-title"><span>↙</span> Income <em>'+income.length+' entries</em></div>'+income.map(x=>x.outerHTML).join('')+'</section>':''}${expense.length?'<section class="entry-group expense-group"><div class="group-title expense-title"><span>↗</span> Expenses <em>'+expense.length+' entries</em></div>'+expense.map(x=>x.outerHTML).join('')+'</section>':''}`;stackingGroups=false;}
new MutationObserver(()=>setTimeout(stackGroups,0)).observe($('#allEntries'),{childList:true});
const typeChooser=$('.segmented');const donationOption=document.createElement('label');donationOption.innerHTML='<input type="radio" name="entryType" value="donation" /><span>Donation</span>';typeChooser.insertBefore(donationOption,typeChooser.lastElementChild);const donationDetailField=document.createElement('label');donationDetailField.id='donationDetailField';donationDetailField.className='wide hidden';donationDetailField.innerHTML='<span>Donation type / donated item</span><input id="entryDonationDetail" placeholder="What will be donated? e.g. Flower, Saree, Food" />';$('#entryCategory').closest('label').before(donationDetailField);donationOption.querySelector('input').onchange=toggleType;
donationDetailField.insertAdjacentHTML('afterbegin','<span>Donation type</span><select id="donationKind"><option value="cash">Cash Donation</option><option value="item">Item Donation</option></select>');
$('#donationKind').onchange=()=>{$('#entryDonationDetail').required=$('#donationKind').value==='item';$('#entryDonationDetail').placeholder=$('#donationKind').value==='item'?'What item will be donated? e.g. Flower, Saree, Food':'Optional cash donation note';};
function updateDonationDetailVisibility(){const item=$('#donationKind').value==='item';$('#entryDonationDetail').classList.toggle('hidden',!item);$('#entryDonationDetail').required=item;$('#entryAmount').required=!item;const labels=donationDetailField.querySelectorAll('span');if(labels[1])labels[1].textContent=item?'Item description':'Donation details';}$('#donationKind').addEventListener('change',updateDonationDetailVisibility);updateDonationDetailVisibility();
$('#entryForm').addEventListener('submit',()=>setTimeout(()=>{const latest=state.entries[0];if(latest?.type==='donation'){latest.person=$('#entryPerson').value.trim();latest.particular=$('#entryDonationDetail').value.trim();latest.donationKind=$('#donationKind').value;latest.category=latest.donationKind==='cash'?'Cash Donation':'Item Donation';save();render();}},60));
let donationStacking=false;
function splitDonationCard(){const node=$('#allEntries');if(!node||donationStacking||node.querySelector('.donation-group'))return;const entries=[...node.querySelectorAll('.entry')];const donations=entries.filter(x=>x.querySelector('.entry-icon.donation')),cashDonations=donations.filter(x=>x.querySelector('.entry-meta')?.textContent.includes('Cash Donation')),itemDonations=donations.filter(x=>!x.querySelector('.entry-meta')?.textContent.includes('Cash Donation'));const income=entries.filter(x=>!x.querySelector('.entry-amount.expense')&&!x.querySelector('.entry-icon.donation')),expense=entries.filter(x=>x.querySelector('.entry-amount.expense'));const totalFor=list=>list.reduce((sum,card)=>sum+Number(state.entries.find(entry=>entry.id===card.dataset.entryId)?.amount||0),0);const incomeTotal=totalFor(income),cashTotal=totalFor(cashDonations),itemTotal=totalFor(itemDonations),expenseTotal=totalFor(expense);donationStacking=true;node.innerHTML=`${income.length?'<section class="entry-group income-group"><div class="group-title income-title"><span>↙</span> Income <em>'+income.length+' entries</em></div>'+income.map(x=>x.outerHTML).join('')+'<div class="group-total"><span>Total income</span><strong>'+money(incomeTotal)+'</strong></div></section>':''}<section class="entry-group donation-group"><div class="group-title donation-title"><span>✦</span> Cash Donations <em>${cashDonations.length} entries</em></div>${cashDonations.length?cashDonations.map(x=>x.outerHTML).join(''):'<div class="group-empty">No cash donations yet</div>'}<div class="group-total"><span>Total cash donated</span><strong>${money(cashTotal)}</strong></div></section><section class="entry-group misc-donation-group"><div class="group-title misc-title"><span>✦</span> Misc. Donations <em>${itemDonations.length} entries</em></div>${itemDonations.length?itemDonations.map(x=>x.outerHTML).join(''):'<div class="group-empty">No item donations yet</div>'}<div class="group-total"><span>Total item donation value</span><strong>${money(itemTotal)}</strong></div></section>${expense.length?'<section class="entry-group expense-group"><div class="group-title expense-title"><span>↗</span> Expenses <em>'+expense.length+' entries</em></div>'+expense.map(x=>x.outerHTML).join('')+'<div class="group-total"><span>Total expense</span><strong>'+money(expenseTotal)+'</strong></div></section>':''}`;donationStacking=false;}
new MutationObserver(()=>setTimeout(splitDonationCard,0)).observe($('#allEntries'),{childList:true});
new MutationObserver(()=>document.querySelectorAll('.income-group .group-total span').forEach(label=>{if(label.textContent!=='Total income')label.textContent='Total income';})).observe($('#allEntries'),{childList:true,subtree:true});
document.querySelector('[data-year="2025"]')?.remove();setTimeout(()=>{if(state.activeYear!=='2026'){state.activeYear='2026';state.entries=state.entriesByYear['2026']||[];render();}},350);
setTimeout(()=>{const current=state.entriesByYear['2026']||[],hidden=state.entriesByYear['2025']||[],isSeeded=current.length===seedSubscription.length&&current.every(entry=>entry.notes==='Imported from 2025 balance sheet');if(isSeeded){state.entriesByYear['2026']=[];state.activeYear='2026';state.entries=[];save();render();}else if(!current.length&&hidden.length&&hidden.length<seedSubscription.length){state.entriesByYear['2026']=hidden;state.activeYear='2026';state.entries=hidden;save();render();}},450);
const printReport=document.createElement('div');printReport.id='printReport';document.body.appendChild(printReport);function reportTable(title,columns,rows,totalLabel,total){return `<section class="print-section"><h2>${title}</h2><table><thead><tr>${columns.map(column=>`<th>${column}</th>`).join('')}</tr></thead><tbody>${rows||'<tr><td colspan="'+columns.length+'" class="print-empty">No entries</td></tr>'}</tbody>${totalLabel?`<tfoot><tr><td colspan="${columns.length-1}">${totalLabel}</td><td>${money(total)}</td></tr></tfoot>`:''}</table></section>`}function renderPrintReport(){const entries=state.entries.slice().sort(sortDate),income=entries.filter(e=>e.type==='income'),cash=entries.filter(e=>e.type==='donation'&&e.donationKind==='cash'),misc=entries.filter(e=>e.type==='donation'&&e.donationKind!=='cash'),expense=entries.filter(e=>e.type==='expense'),sum=list=>list.reduce((total,e)=>total+Number(e.amount||0),0),row=(cells)=>`<tr>${cells.map(cell=>`<td>${cell}</td>`).join('')}</tr>`;printReport.innerHTML=`<div class="print-page"><header class="print-header"><div><p>PAL BHAVAN</p><h1>Durga Puja ${state.activeYear}</h1><span>Income & Expense Statement</span></div><div class="print-date">Prepared on<br><strong>${new Date().toLocaleDateString('en-IN')}</strong></div></header><div class="print-summary"><div><span>Total collection</span><strong>${money(sum(income)+sum(cash))}</strong></div><div><span>Cash donated</span><strong>${money(sum(cash))}</strong></div><div><span>Total expenses</span><strong>${money(sum(expense))}</strong></div><div class="final"><span>Current balance</span><strong>${money(sum(income)+sum(cash)-sum(expense))}</strong></div></div>${reportTable('Income',['Date','Contributor','Payment','Amount','Notes'],income.map(e=>row([esc(e.date),esc(e.person),esc(e.mode),money(e.amount),esc(e.notes||'—')])).join(''),'Total income',sum(income))}${reportTable('Cash Donation',['Date','Donor','Payment','Amount','Notes'],cash.map(e=>row([esc(e.date),esc(e.person),esc(e.mode),money(e.amount),esc(e.notes||'—')])).join(),'Total cash donated',sum(cash))}${reportTable('Misc. Donation',['Date','Donor','Item / description','Value','Notes'],misc.map(e=>row([esc(e.date),esc(e.person),esc(e.particular||'—'),money(e.amount),esc(e.notes||'—')])).join(),'Total item donation value',sum(misc))}${reportTable('Expenses',['Date','Particular','Payment','Amount','Notes'],expense.map(e=>row([esc(e.date),esc(e.particular),esc(e.mode),money(e.amount),esc(e.notes||'—')])).join(),'Total expense',sum(expense))}<footer class="print-footer"><span>Pal Bhavan Durga Puja ${state.activeYear}</span><span>Generated from Pujo Ledger</span></footer></div>`;}$('#printBtn').onclick=()=>{renderPrintReport();window.print();};
function alignPrintTotals(){printReport.querySelectorAll('tfoot tr').forEach(row=>{const cells=[...row.children];if(cells.length===2){const amount=cells[1];const spacer=document.createElement('td');row.insertBefore(spacer,amount);cells[0].colSpan=3;}})}$('#printBtn').onclick=()=>{renderPrintReport();alignPrintTotals();window.print();};
let activeEntryGroup='all';const entryGroupTabs=document.createElement('div');entryGroupTabs.className='entry-group-tabs';entryGroupTabs.innerHTML='<button class="entry-group-tab active" data-entry-group="all">All</button><button class="entry-group-tab" data-entry-group="income">Income</button><button class="entry-group-tab" data-entry-group="donation">Cash Donation</button><button class="entry-group-tab" data-entry-group="misc-donation">Misc. Donation</button><button class="entry-group-tab" data-entry-group="expense">Expense</button>';$('#allEntries').before(entryGroupTabs);function applyEntryGroupTab(){entryGroupTabs.querySelectorAll('.entry-group-tab').forEach(b=>b.classList.toggle('active',b.dataset.entryGroup===activeEntryGroup));$('#allEntries').querySelectorAll('.entry-group').forEach(group=>{const matches=activeEntryGroup==='all'||group.classList.contains(activeEntryGroup+'-group');group.style.display=matches?'flex':'none';});}entryGroupTabs.onclick=e=>{const button=e.target.closest('.entry-group-tab');if(button){activeEntryGroup=button.dataset.entryGroup;applyEntryGroupTab();}};new MutationObserver(applyEntryGroupTab).observe($('#allEntries'),{childList:true});
$('#allEntries').addEventListener('click',e=>{if(e.target.closest('button'))return;const group=e.target.closest('.entry-group');if(!group)return;activeEntryGroup=group.classList.contains('income-group')?'income':group.classList.contains('donation-group')?'donation':group.classList.contains('misc-donation-group')?'misc-donation':group.classList.contains('expense-group')?'expense':'all';applyEntryGroupTab();});
new MutationObserver(()=>$('#heroYear').textContent=$('#yearTitle').textContent).observe($('#yearTitle'),{childList:true,characterData:true,subtree:true});
new MutationObserver(()=>$('#balanceTotal').classList.toggle('negative',$('#balanceTotal').textContent.includes('-'))).observe($('#balanceTotal'),{childList:true,characterData:true,subtree:true});
function syncBalanceColor(){const balance=$('#balanceTotal');if(balance)balance.classList.toggle('negative',/[-−]/.test(balance.textContent));}syncBalanceColor();setInterval(syncBalanceColor,300);
document.querySelectorAll('[data-action="new"]').forEach(button=>button.onclick=()=>typeof openEntry==='function'?openEntry():$('#entryDialog').showModal());
const stats=$('.stats');const cashCard=$('#cashDonationTotal')?.closest('article');new MutationObserver(()=>{const total=state.entries.filter(e=>e.type==='donation'&&e.donationKind==='cash').reduce((sum,e)=>sum+Number(e.amount||0),0);$('#cashDonationTotal').textContent=money(total);}).observe($('#incomeTotal'),{childList:true,characterData:true,subtree:true});
let incomeSyncing=false;let lastIncomeTotal='';new MutationObserver(()=>{if(incomeSyncing)return;const total=state.entries.filter(e=>e.type!=='expense').reduce((sum,e)=>sum+Number(e.amount||0),0),formatted=money(total);if(formatted===lastIncomeTotal)return;lastIncomeTotal=formatted;incomeSyncing=true;$('#incomeTotal').textContent=formatted;$('#incomeCount').textContent=state.entries.filter(e=>e.type!=='expense').length+' entries';incomeSyncing=false;}).observe($('#incomeTotal'),{childList:true,characterData:true,subtree:true});
$('#entryCategory').closest('label').classList.add('hidden');$('#categoriesList').closest('.panel').classList.add('hidden');let categoryHiddenSync=false;function hideCategoryText(){if(categoryHiddenSync)return;categoryHiddenSync=true;document.querySelectorAll('.entry-meta').forEach(meta=>{if(meta.closest('.entry')?.querySelector('.entry-icon.donation'))return;const parts=meta.textContent.split(' · ');if(parts.length>1)meta.textContent=parts.slice(1).join(' · ')});categoryHiddenSync=false;}hideCategoryText();new MutationObserver(hideCategoryText).observe(document.body,{childList:true,subtree:true});
$('#printBtn').onclick=()=>{renderPrintReport();printReport.querySelector('.print-header h1').textContent=`Pal Barir Durga Pujo ${state.activeYear}`;alignPrintTotals();window.print();};
$('#syncCode')?.addEventListener('change',()=>{state.syncToken=$('#syncCode').value.trim();save();});
$('#pushSyncBtn')?.addEventListener('click',()=>{state.syncToken=$('#syncCode').value.trim();save();pushCloudState();});
$('#pullSyncBtn')?.addEventListener('click',()=>{state.syncToken=$('#syncCode').value.trim();pullCloudState();});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushCloudSync()});window.addEventListener('pagehide',flushCloudSync);
function openEntryGroup(group){showView('entries');activeEntryGroup=group;applyEntryGroupTab();$('#entriesView').scrollIntoView({behavior:'smooth',block:'start'});}
$('#incomeTotal')?.closest('article')?.addEventListener('click',()=>openEntryGroup('income'));
$('#expenseTotal')?.closest('article')?.addEventListener('click',()=>openEntryGroup('expense'));
$('#cashDonationTotal')?.closest('article')?.addEventListener('click',()=>openEntryGroup('donation'));
document.addEventListener('click',e=>{const imageButton=e.target.closest('.entry-image-link');if(imageButton){$('#lightboxImage').src=imageButton.dataset.image;$('#imageDialog').showModal();return;}if(e.target.closest('[data-image-close]'))$('#imageDialog')?.close();});
$('#imageDialog')?.addEventListener('click',e=>{if(e.target===$('#imageDialog'))$('#imageDialog').close();});
document.addEventListener('click',e=>{const remove=e.target.closest('[data-remove-image]');if(remove)remove.closest('.image-thumb')?.remove();});
$('#entryForm')?.addEventListener('submit',()=>setTimeout(()=>{const id=$('#entryId').value,entry=state.entries.find(item=>item.id===id);if(entry){entry.images=[...$('#imagePreview').querySelectorAll('.entry-image-link')].map(button=>button.dataset.image);save();}},90));
function downloadExcel(){const entries=state.entries.slice().sort(sortDate),income=entries.filter(e=>e.type==='income').reduce((sum,e)=>sum+Number(e.amount||0),0),cash=entries.filter(e=>e.type==='donation'&&e.donationKind==='cash').reduce((sum,e)=>sum+Number(e.amount||0),0),expense=entries.filter(e=>e.type==='expense').reduce((sum,e)=>sum+Number(e.amount||0),0),cell=value=>`<td>${esc(value??'')}</td>`,rows=entries.map(e=>`<tr>${cell(e.date)}${cell(e.type==='expense'?'Expense':e.type==='donation'?(e.donationKind==='cash'?'Cash Donation':'Misc. Donation'):'Income')}${cell(e.person||e.particular||'')}${cell(e.particular||'')}${cell(e.mode)}${cell(e.amount)}${cell(e.notes||'')}${cell(e.images?.length?`${e.images.length} image(s)`:'' )}</tr>`).join(''),html=`<html><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Arial}th,td{border:1px solid #999;padding:6px;text-align:left}th{background:#f0d39b}tfoot td{font-weight:bold}</style></head><body><h2>${esc(ledgerLabels[state.activeLedger]||'Ledger')} ${esc(state.activeYear)}</h2><table><thead><tr><th>Date</th><th>Type</th><th>Name / Particular</th><th>Item / Description</th><th>Payment mode</th><th>Amount</th><th>Notes</th><th>Images</th></tr></thead><tbody>${rows||'<tr><td colspan="8">No entries</td></tr>'}</tbody><tfoot><tr><td colspan="5">Total income</td><td>${income}</td><td colspan="2"></td></tr><tr><td colspan="5">Cash donations</td><td>${cash}</td><td colspan="2"></td></tr><tr><td colspan="5">Total expense</td><td>${expense}</td><td colspan="2"></td></tr><tr><td colspan="5">Current balance</td><td>${income+cash-expense}</td><td colspan="2"></td></tr></tfoot></table></body></html>`,blob=new Blob([html],{type:'application/vnd.ms-excel'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${ledgerLabels[state.activeLedger]||'ledger'}-${state.activeYear}.xls`;link.click();URL.revokeObjectURL(link.href);toast('Excel file downloaded')}
const excelButton=document.createElement('button');excelButton.id='excelBtn';excelButton.className='secondary';excelButton.type='button';excelButton.textContent='Download Excel file';$('#exportBtn')?.after(excelButton);excelButton.addEventListener('click',downloadExcel);
function downloadSheetsCsv(){const entries=state.entries.slice().sort(sortDate),income=entries.filter(e=>e.type==='income').reduce((sum,e)=>sum+Number(e.amount||0),0),cash=entries.filter(e=>e.type==='donation'&&e.donationKind==='cash').reduce((sum,e)=>sum+Number(e.amount||0),0),expense=entries.filter(e=>e.type==='expense').reduce((sum,e)=>sum+Number(e.amount||0),0),csvCell=value=>`"${String(value??'').replace(/"/g,'""')}"`,rows=[['Date','Type','Name / Particular','Item / Description','Payment mode','Amount','Notes','Images'],...entries.map(e=>[e.date,e.type==='expense'?'Expense':e.type==='donation'?(e.donationKind==='cash'?'Cash Donation':'Misc. Donation'):'Income',e.person||e.particular||'',e.particular||'',e.mode,e.amount,e.notes||'',e.images?.length?`${e.images.length} image(s)`:'' ]),[],['Total income','','','','',income],['Cash donations','','','','',cash],['Total expense','','','','',expense],['Current balance','','','','',income+cash-expense]],blob=new Blob(['\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${ledgerLabels[state.activeLedger]||'ledger'}-${state.activeYear}.csv`;link.click();URL.revokeObjectURL(link.href);toast('Excel / Google Sheets file downloaded')}
const sheetsButton=excelButton.cloneNode(true);sheetsButton.textContent='Download Excel / Sheets CSV';excelButton.replaceWith(sheetsButton);sheetsButton.addEventListener('click',downloadSheetsCsv);
const baseOpenEntry=openEntry;openEntry=function(entry){baseOpenEntry(entry);if(entry?.type==='donation'&&$('#donationKind')){$('#donationKind').value=entry.donationKind||'cash';$('#entryDonationDetail').value=entry.particular||'';updateDonationDetailVisibility()}};
$('#entryForm')?.addEventListener('submit',()=>setTimeout(()=>{const id=$('#entryId').value,entry=state.entries.find(item=>item.id===id);if(entry?.type==='donation'){entry.person=$('#entryPerson').value.trim();entry.particular=$('#entryDonationDetail').value.trim();entry.donationKind=$('#donationKind').value;entry.category=entry.donationKind==='cash'?'Cash Donation':'Item Donation';save();render()}},120));
function applyPrintColors(){const income=state.entries.filter(e=>e.type==='income').reduce((sum,e)=>sum+Number(e.amount||0),0),cash=state.entries.filter(e=>e.type==='donation'&&e.donationKind==='cash').reduce((sum,e)=>sum+Number(e.amount||0),0),expense=state.entries.filter(e=>e.type==='expense').reduce((sum,e)=>sum+Number(e.amount||0),0),balance=income+cash-expense;printReport.querySelector('.print-summary div:nth-child(3)')?.classList.add('expense-total');const final=printReport.querySelector('.print-summary .final');final?.classList.toggle('positive',balance>=0);final?.classList.toggle('negative',balance<0);printReport.querySelectorAll('.print-section h2').forEach(heading=>heading.classList.toggle('green-heading',heading.textContent!=='Expenses'));}
$('#printBtn').onclick=()=>{renderPrintReport();printReport.querySelector('.print-header h1').textContent=`Pal Barir Durga Pujo ${state.activeYear}`;alignPrintTotals();applyPrintColors();window.print();};
